# Generated by Django 4.1.5 on 2023-01-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userLogin',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'student_id',
            },
        ),
    ]
