# Generated by Django 4.1.5 on 2023-01-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investApp', '0002_alter_userlogin_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='team1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='team2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='team3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='team4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='team5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user_team',
            field=models.IntegerField(default=0),
        ),
    ]
