# Generated by Django 4.1.5 on 2023-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investApp', '0003_userlogin_team1_userlogin_team2_userlogin_team3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='user_money',
            field=models.IntegerField(default=10000000),
        ),
    ]
